-- E-Commerce Analytics Platform - Snowflake Setup
-- Run this to initialize your Snowflake environment

-- Create databases
CREATE DATABASE IF NOT EXISTS ECOMMERCE_DEV;
CREATE DATABASE IF NOT EXISTS ECOMMERCE_PROD;

-- Create schemas for dev
USE DATABASE ECOMMERCE_DEV;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;

-- Create schemas for prod
USE DATABASE ECOMMERCE_PROD;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Grant permissions (adjust as needed)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ACCOUNTADMIN;
GRANT ALL ON DATABASE ECOMMERCE_DEV TO ROLE ACCOUNTADMIN;
GRANT ALL ON DATABASE ECOMMERCE_PROD TO ROLE ACCOUNTADMIN;

-- Set context
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ECOMMERCE_DEV;
USE SCHEMA RAW;

SELECT 'Snowflake setup complete!' AS STATUS;
